<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class MaterialByQuantitySeeder extends Seeder
{
    public function run()
    {
        $mainType = [
            'Lumber',
            'Lumber',
            'Lumber',
            'Lumber',
            'Lumber',
            'Lumber',
            'Lumber',
            'Lumber',
            'Lumber',
            'Wood Panels',
            'Wood Panels',
            'Wood Panels',
            'Wood Panels',
            'Exterior',
            'Exterior',
            'Packing panels',
            'Packing panels',
            'Packing panels',
            'Packing panels',
            'Packing panels',
            'Packing panels',
            'Foam',
            'Foam',
            'Foam',
            'Foam',
            'Foam',
            'Foam',
            'Foam',
            'Foam',
            'Foam',
            'Interior',
            'Interior',
            'Interior',
            'Interior',
            'Interior',
            'Interior',
            'Interior',
            'Interior',
            'Interior',
            'Gasket',
            'Caulking',
            'Adhesive',
            'Tape',
            'Tape',
            'Tape',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Hardware',
            'Coating'
        ];

        $materialType = [
            '1/2\" AC plywood',
            '3/4\" AC plywood',
            '1x4 Pine',
            '1x6 Pine',
            '2x4 Pine',
            '4x4 Pine',
            '18mm PEFC III Spruce',
            '12mm PEFC III Spruce',
            '25 x 100 Redwood',
            '3/8" AC plywood',
            '18mm and 12mm far eastern plywood',
            '1/2" MDO',
            '3/4" MDO',
            'Fiberglass composite',
            'Aluminum',
            'Cardboard 3/16" single wall',
            '1/8 Acid Free Cardboard',
            '1/4 Acid Free Cardboard',
            'Foamcore 3/16"',
            'Foamcore 1/2"',
            'Coroplast',
            '1" ethafoam',
            '2" ethafom',
            '1" grey foam / esterfoam',
            '2" grey foam / esterfoam',
            '2.2 Celluplank',
            '4.0 Celluplank',
            '2" Insulfoam/laminate faced polystyrene',
            'Volara',
            'RPET foam',
            'Tyvek',
            'Marvelseal',
            'Polygal',
            'Masonite',
            'PP velour',
            '50mm or 100mm F133 foam',
            'LD33 Black foam gasket 3mm',
            'LD33 Plastazote',
            'LD45 Plastazote',
            'Neoprene',
            'Caulking',
            'Wood Glue',
            'EVA Tape',
            'Artist\'s Paper Tape',
            'Duct Tape',
            'Large oz clips',
            'Metal handles',
            'Bolt plate',
            'Butterfly clilps',
            'Stainless Bolt',
            'Screws & Nails',
            'Stainless Screws',
            'Staples',
            '38mm and 80mm galvanised corrosion resistant ring nails',
            '25mm and 50mm grade polystyrene',
            '30mm, 60mm, 80mm Prodrive screws',
            'Steel Bolt',
            'Water based polyurethane'
        ];

        $embodiedCarbonFactorUnitPerKg = [
            0.795,
            0.795,
            0.137,
            0.137,
            0.137,
            0.137,
            0.310,
            0.310,
            0.100,
            0.795,
            0.795,
            1.077,
            1.077,
            8.701,
            5.469,
            0.901,
            0.940,
            0.940,
            2.146,
            2.146,
            3.069,
            2.396,
            2.396,
            5.059,
            5.059,
            2.396,
            2.396,
            4.038,
            2.396,
            1.776,
            4.156,
            2.288,
            7.731,
            0.857,
            2.657,
            5.059,
            2.396,
            2.396,
            2.396,
            2.678,
            3.160,
            5.400,
            2.333,
            1.866,
            2.333,
            5.535,
            1.289,
            1.289,
            1.542,
            4.068,
            1.710,
            4.068,
            1.710,
            1.710,
            3.455,
            1.800,
            1.289,
            3.655
        ];

        $dataSources = [
            'EC3',
            'EC3',
            'CORRIM',
            'CORRIM',
            'CORRIM',
            'CORRIM',
            'WISA',
            'WISA',
            'CORRIM',
            'EC3',
            'EC3',
            'CORRIM',
            'CORRIM',
            'ecoinvent',
            'ecoinvent',
            'ecoinvent',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'ecoinvent',
            'STiCH',
            'ecoinvent',
            'DuPont',
            'STiCH',
            'ecoinvent',
            'CORRIM',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'STiCH',
            'ecoinvent',
            'ecoinvent',
            'EPiC',
            'ecoinvent',
            'industry',
            'ecoinvent',
            'ecoinvent',
            'ecoinvent',
            'ecoinvent',
            'ecoinvent',
            'ecoinvent',
            'galvanizeit',
            'ecoinvent',
            'galvanizeit',
            'galvanizeit',
            'STiCH',
            'ecoinvent',
            'ecoinvent',
            'Sherwin-Williams'
        ];

        $sites = [
            null,
            null,
            'https://corrim.org/corrimdev/wp-content/uploads/2020/06/AWC_EPD_NorthAmericanSoftwoodLumber_20200605.pdf',
            'https://corrim.org/corrimdev/wp-content/uploads/2020/06/AWC_EPD_NorthAmericanSoftwoodLumber_20200605.pdf',
            'https://corrim.org/corrimdev/wp-content/uploads/2020/06/AWC_EPD_NorthAmericanSoftwoodLumber_20200605.pdf',
            'https://corrim.org/corrimdev/wp-content/uploads/2020/06/AWC_EPD_NorthAmericanSoftwoodLumber_20200605.pdf',
            'https://www.wisaplywood.com/siteassets/documents/certificates/epd-uncoated-wisa-spruce-plywood.pdf',
            'https://www.wisaplywood.com/siteassets/documents/certificates/epd-uncoated-wisa-spruce-plywood.pdf',
            'https://corrim.org/corrimdev/wp-content/uploads/2020/06/AWC_EPD_RedwoodLumber_20200605.pdf',
            null,
            null,
            'https://corrim.org/corrimdev/wp-content/uploads/2019/06/CPA_EPD_MDF_Transparency-Summary.pdf',
            'https://corrim.org/corrimdev/wp-content/uploads/2019/06/CPA_EPD_MDF_Transparency-Summary.pdf',
            'glass fibre reinforced plastic, polyamide, injection moulded//[GLO] market for glass fibre reinforced plastic, polyamide, injection moulded',
            'aluminium, cast alloy//[GLO] market for aluminium, cast alloy',
            'corrugated board box//[RER] corrugated board box production',
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            'polystyrene foam slab//[RER] polystyrene foam slab production',
            null,
            null,
            'https://www.pinkbatts.co.nz/assets/EPD-Tyvek-Supro-Tyvek-2506B.pdf',
            null,
            'polycarbonate//[GLO] market for polycarbonate',
            'https://corrim.org/wp-content/uploads/2017/12/CPA_EPD_Hardboard.pdf',
            null,
            null,
            null,
            null,
            null,
            'synthetic rubber//[GLO] market for synthetic rubber',
            'silicone product//[RoW] market for silicone product',
            'https://melbourne.figshare.com/articles/dataset/EPiC_database_-_Wood_glue_PVA_/9979994/1',
            'ethylene vinyl acetate copolymer//[RoW] market for ethylene vinyl acetate copolymer',
            'https://shop.sourceful.com/buy/self-adhesive-tape',
            'ethylene vinyl acetate copolymer//[RoW] market for ethylene vinyl acetate copolymer',
            'brass//[RoW] market for brass',
            'steel, low-alloyed//[GLO] market for steel, low-alloyed',
            'steel, low-alloyed//[GLO] market for steel, low-alloyed',
            'steel, low-alloyed, hot rolled//[GLO] market for steel, low-alloyed, hot rolled',
            'steel, chromium steel 18/8//[GLO] market for steel, chromium steel 18/8',
            'https://galvanizeit.org/uploads/default/2022-EPD-AGA-Hot-Dip-Galvanized-Steel-After-Fabrication.pdf',
            'steel, chromium steel 18/8//[GLO] market for steel, chromium steel 18/8',
            'https://galvanizeit.org/uploads/default/2022-EPD-AGA-Hot-Dip-Galvanized-Steel-After-Fabrication.pdf',
            'https://galvanizeit.org/uploads/default/2022-EPD-AGA-Hot-Dip-Galvanized-Steel-After-Fabrication.pdf',
            null,
            'steel, unalloyed//[GLO] market for steel, unalloyed',
            'steel, low-alloyed//[GLO] market for steel, low-alloyed',
            'https://info.nsf.org/Certified/Sustain/ProdCert/EPD10286.pdf'
        ];

        $notes = [
            'average of 42 EPDs, density 515 kg/m3',
            'average of 42 EPDs, density 515 kg/m3',
            null,
            null,
            null,
            null,
            'density 460 kg/m3',
            'density 460 kg/m3',
            'density 380 kg/m3',
            'average of 42 EPDs, density 515 kg/m3',
            'average of 42 EPDs, density 515 kg/m3',
            'density 705 kg/m3',
            'density 705 kg/m3',
            null,
            null,
            null,
            null,
            null,
            'backing boards study',
            'backing boards study',
            'backing boards study',
            'PE granulate + foaming process',
            'PE granulate + foaming process',
            'PU flexible foam',
            'PU flexible foam',
            'PE granulate + foaming process',
            'PE granulate + foaming process',
            null,
            'PE granulate + foaming process',
            'recycled PET granulate + foaming process',
            null,
            '184 gsm',
            null,
            'density 768 kg/m3',
            'not specific to velour',
            'PU flexible foam',
            'PE granulate + foaming process',
            'PE granulate + foaming process',
            'PE granulate + foaming process',
            'polychloroprene, not specific',
            null,
            'PVA',
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        ];

        $materialByQuantityInCrateDesign = [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
            11,
            12,
            13,
            14,
            15,
            16,
            17,
            18,
            19,
            20,
            21,
            22,
            23,
            24,
            25,
            26,
            27,
            28,
            29,
            30,
            31,
            32,
            33,
            34,
            35,
            36,
            37,
            38,
            39,
            40,
            41,
            42,
            43,
            44,
            45,
            46,
            47,
            48,
            49,
            50,
            51,
            52,
            53,
            54,
            55,
            56,
            57,
            58
        ];

        $materialByQuantityModelInstance = model('MaterialByQuantityModel');

        foreach($mainType as $key => $row) {
            $data = [];
            $data['main_type'] = $row;
            $data['material_type'] = $materialType[$key];
            $data['weight_in_kg'] = 0.000;
            $data['embodied_carbon_factor_unit_per_kg'] = $embodiedCarbonFactorUnitPerKg[$key];
            $data['embodied_carbon_factor_in_kg'] = 0;
            $data['data_source'] = $dataSources[$key];
            $data['site_link'] = $sites[$key];
            $data['notes'] = $notes[$key];
            $data['crate_design_value'] = $materialByQuantityInCrateDesign[$key];
            $data['created_by'] = 1;
            $materialByQuantityModelInstance->insert($data);
        }
    }
}
